name: CI

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov

      envs: |
        - linux: py37-test
        - linux: py38-test
        - linux: py39-test
        - linux: py310-test

        - macos: py37-test
        - macos: py38-test
        - macos: py39-test

        - windows: py37-test
        - windows: py38-test
        - windows: py39-test

  uncovered:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: false
      pytest: false

      envs: |
        - linux: codestyle

        - linux: py37-notebooks
        - windows: py39-notebooks
        - linux: py310-notebooks

        - linux: py37-docs
        - windows: py38-docs

  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      test_extras: test
      test_command: pytest --pyargs glue_jupyter
    secrets:
      pypi_token: ${{ secrets.pypi_token }}

  allowed_failures:
    # some (all?!?) macOS targets are failing on GH actions without any output or explanation
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov

      envs: |
        - macos: py310-test

        - macos: py38-notebooks
          coverage: false
          pytest: false

        - macos: py37-docs
          coverage: false
          pytest: false
